### PR TITLE
Implementation of SEP12 into specification

### PR DESCRIPTION
**Pull request by jakebeal**

### CODE REVIEW

**Comment by jakebeal** [comment]
Note that as a side effect of this update, the UML source for Nic's diagrams has also been added to the spec repository.

**Comment by cjmyers** [comment]
I think if "any" wasDerivedFrom has same persistentIdentity then it should have an earlier version, rather than just "one of".  Otherwise, changes look fine.

**Comment by jakebeal** [comment]
Comment incorporated.

**Comment by jakebeal** [comment]
Hearing satisfaction from Chris, and no other comments, I am performing this merge.

**Pull request merged**
