### PR TITLE
Changing 2.0 to 2.1, 2.x or just 2 as appropriate

### PR DESCRIPTION
**Pull request by jakebeal**
I found that some places needed to have the version number changed differently than others, in order to make most grammatical or narrative sense.  I think it should be reviewed by others.

### CODE REVIEW

**Comment by jakebeal** [comment]
Fixes Issue #76

**Comment by jakebeal** [comment]
Raik has reviewed and approved; merging.

**Comment by cjmyers** [comment]
Basically looks okay, though there is one place in Overview of SBOL that you say SBOL 2 standards allows, so this should either be SBOL 2 standard allows OR SBOL 2 standards allow.  I think I like the former.

BTW: in some places you say SBOL 2.x and others SBOL 2.  I’m not sure the rule you used to decide.  Do you think we could perhaps change 2.x to 2, in all cases?  Is it important to indicate any difference?  We could just say 2.x and 2 mean the same thing, namely 2 means any version that starts with a 2.

**Comment by jakebeal** [comment]
Isn't that typo fixed in 23ba89db25e9d3576cdd20a28c823b08fc977a1b, or did you find another one?

Regarding 2.x vs. 2, I had a system:
* I used 2 for statements about the general philosophy of the whole 2-series data model, typically in comparison with 1.0 or 1.1
* I used 2.x to refer to things that are true of 2.0 and 2.1 and likely but not necessary to stay so in future 2-series revisions.  For example, I use 2.x to discuss the current set of classes, because in 2.2 we might add a new backward-compatible class; that updated diagram would then become 2.2-specific and no longer apply to 2.0 and 2.1.

**Comment by cjmyers** [comment]
> On Oct 25, 2016, at 7:58 PM, Jacob Beal <notifications@github.com> wrote:
> 
> Isn't that typo fixed in 23ba89d <https://github.com/SynBioDex/SBOL-specification/commit/23ba89db25e9d3576cdd20a28c823b08fc977a1b>, or did you find another one?
> 
Yes, I must have had a slightly older version.
> Regarding 2.x vs. 2, I had a system:
> 
> I used 2 for statements about the general philosophy of the whole 2-series data model, typically in comparison with 1.0 or 1.1
> I used 2.x to refer to things that are true of 2.0 and 2.1 and likely but not necessary to stay so in future 2-series revisions. For example, I use 2.x to discuss the current set of classes, because in 2.2 we might add a new backward-compatible class; that updated diagram would then become 2.2-specific and no longer apply to 2.0 and 2.1.
I’m still not sure I like the 2.x notation.  To me, this is the same as 2.<anything> which is the same as 2 to me.  I would prefer to use SBOL 2 in places where you are currently using 2.x, and assume SBOL 2 means the SBOL 2 versions.  When you want to say something specific that has changed, then you can use specific statements like, “a change from SBOL 2.0 to SBOL 2.1 is…”.  I think it is awkward that we use SBOL 1.1 statements as it begs the question what was SBOL 1.0?  I don’t think any of us remember the distinction between the two (or at least very few people do).  The major version numbers are what should be important in my opinion for the general audience.  Anyway, not a huge deal either way, just my two cents.

**Pull request merged**
