### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by jonrodness**
* fix typos in spec

### CODE REVIEW

**Comment by tcmitchell** [comment]
@cjmyers What are your thoughts on "A SBOL" vs. "An SBOL"? It looks like the spec uses "a" instead of "an". I assume this has been discussed in the past.

**Comment by jakebeal** [comment]
Since people generally pronounce it "ess-ball", I generally embrace "an"

**Comment by cjmyers** [comment]
I don't have a strong feeling about it, as long as we are consistent.

**Comment by jonrodness** [comment]
> Since people generally pronounce it "ess-ball", I generally embrace "an"

From what I have read, this seems to be the correct way or acronyms. It would "sound" incorrect, otherwise.

**Review by tcmitchell — APPROVED** [review]

**Pull request merged**
